/**
 * GrowthForge Buyer Intelligence Engine
 * Workflow State Machine Specification
 * 
 * Strict Application-Controlled State Transitions.
 * AI agents must not freely change workflow state.
 */

export const WORKFLOW_STATES = {
  RAW: 'RAW',
  RESOLVED: 'RESOLVED',
  ENRICHING: 'ENRICHING',
  ENRICHED: 'ENRICHED',
  CALL_ELIGIBILITY: 'CALL_ELIGIBILITY',
  CALL_PENDING: 'CALL_PENDING',
  CALLING: 'CALLING',
  CONNECTED: 'CONNECTED',
  QUALIFICATION_IN_PROGRESS: 'QUALIFICATION_IN_PROGRESS',
  QUALIFIED: 'QUALIFIED',
  SCORED: 'SCORED',
  HOT: 'HOT',
  WARM: 'WARM',
  NURTURE: 'NURTURE',
  PROJECT_MATCHED: 'PROJECT_MATCHED',
  HANDOFF: 'HANDOFF',
} as const;

export type StandardWorkflowState = typeof WORKFLOW_STATES[keyof typeof WORKFLOW_STATES];

export const FAILURE_STATES = {
  ENRICHMENT_FAILED: 'ENRICHMENT_FAILED',
  CALL_FAILED: 'CALL_FAILED',
  NO_ANSWER: 'NO_ANSWER',
  INVALID_CONTACT: 'INVALID_CONTACT',
  QUALIFICATION_FAILED: 'QUALIFICATION_FAILED',
  REQUIRES_REVIEW: 'REQUIRES_REVIEW',
} as const;

export type FailureWorkflowState = typeof FAILURE_STATES[keyof typeof FAILURE_STATES];

export type WorkflowState = StandardWorkflowState | FailureWorkflowState;

export interface WorkflowTransitionRule {
  from: WorkflowState;
  to: WorkflowState[];
  description: string;
}

export const WORKFLOW_PIPELINE_ORDER: StandardWorkflowState[] = [
  WORKFLOW_STATES.RAW,
  WORKFLOW_STATES.RESOLVED,
  WORKFLOW_STATES.ENRICHING,
  WORKFLOW_STATES.ENRICHED,
  WORKFLOW_STATES.CALL_ELIGIBILITY,
  WORKFLOW_STATES.CALL_PENDING,
  WORKFLOW_STATES.CALLING,
  WORKFLOW_STATES.CONNECTED,
  WORKFLOW_STATES.QUALIFICATION_IN_PROGRESS,
  WORKFLOW_STATES.QUALIFIED,
  WORKFLOW_STATES.SCORED,
  WORKFLOW_STATES.HOT, // or WARM or NURTURE
  WORKFLOW_STATES.PROJECT_MATCHED,
  WORKFLOW_STATES.HANDOFF,
];

/**
 * Valid allowed transitions map ensuring deterministic execution
 */
export const ALLOWED_TRANSITIONS: Record<WorkflowState, WorkflowState[]> = {
  RAW: ['RESOLVED', 'INVALID_CONTACT'],
  RESOLVED: ['ENRICHING', 'CALL_ELIGIBILITY', 'REQUIRES_REVIEW'],
  ENRICHING: ['ENRICHED', 'ENRICHMENT_FAILED'],
  ENRICHED: ['CALL_ELIGIBILITY', 'REQUIRES_REVIEW'],
  CALL_ELIGIBILITY: ['CALL_PENDING', 'REQUIRES_REVIEW', 'NURTURE'],
  CALL_PENDING: ['CALLING', 'CALL_FAILED'],
  CALLING: ['CONNECTED', 'NO_ANSWER', 'CALL_FAILED'],
  CONNECTED: ['QUALIFICATION_IN_PROGRESS', 'CALL_FAILED'],
  QUALIFICATION_IN_PROGRESS: ['QUALIFIED', 'QUALIFICATION_FAILED', 'REQUIRES_REVIEW'],
  QUALIFIED: ['SCORED', 'REQUIRES_REVIEW'],
  SCORED: ['HOT', 'WARM', 'NURTURE'],
  HOT: ['PROJECT_MATCHED', 'HANDOFF'],
  WARM: ['PROJECT_MATCHED', 'HANDOFF'],
  NURTURE: ['PROJECT_MATCHED', 'HANDOFF'],
  PROJECT_MATCHED: ['HANDOFF'],
  HANDOFF: [],
  
  // Failure / Review recovery paths
  ENRICHMENT_FAILED: ['CALL_ELIGIBILITY', 'REQUIRES_REVIEW'],
  CALL_FAILED: ['CALL_PENDING', 'REQUIRES_REVIEW'],
  NO_ANSWER: ['CALL_PENDING', 'NURTURE', 'REQUIRES_REVIEW'],
  INVALID_CONTACT: ['REQUIRES_REVIEW'],
  QUALIFICATION_FAILED: ['REQUIRES_REVIEW', 'NURTURE'],
  REQUIRES_REVIEW: ['CALL_ELIGIBILITY', 'CALL_PENDING', 'QUALIFIED', 'NURTURE'],
};
