-- GrowthForge Buyer Intelligence Engine
-- Seed Data: sample-projects.sql
-- Description: 15 Sample demonstration real-estate projects across major Indian hubs.
-- NOTE: These are demo records for development and testing only.

INSERT INTO projects (
    project_code,
    project_name,
    developer_name,
    city,
    locality,
    micro_market,
    property_type,
    configurations,
    price_min,
    price_max,
    possession,
    project_description,
    features,
    amenities,
    project_url,
    status
) VALUES
(
    'DEMO_PROJECT_001',
    'Prestige Falcon City Phase 2',
    'Prestige Group',
    'Bengaluru',
    'Kanakapura Road',
    'South Bengaluru',
    'Apartment',
    '["2 BHK", "3 BHK", "4 BHK"]'::jsonb,
    11500000.00,
    24500000.00,
    'Dec 2026',
    'High-rise luxury residential development located right next to the Forum Mall and metro connectivity.',
    '["Metro Adjacent", "Forum Mall Access", "Large Open Landscaping", "EV Charging"]'::jsonb,
    '["Clubhouse", "Infinity Pool", "Badminton Court", "Squash Court", "Jogging Track"]'::jsonb,
    'https://example.com/projects/prestige-falcon-city',
    'ACTIVE'
),
(
    'DEMO_PROJECT_002',
    'Godrej Woodsman Serenity',
    'Godrej Properties',
    'Bengaluru',
    'Hebbal',
    'North Bengaluru',
    'Apartment',
    '["3 BHK", "4 BHK"]'::jsonb,
    18500000.00,
    38000000.00,
    'Ready to Move',
    'Forest-themed premium luxury apartments on Bellary Road with express airport connectivity.',
    '["Airport Corridor", "Forest Theme", "Private Decks", "Low Density"]'::jsonb,
    '["Heated Pool", "Private Theatre", "Spa & Sauna", "Tennis Court", "Concierge"]'::jsonb,
    'https://example.com/projects/godrej-woodsman',
    'ACTIVE'
),
(
    'DEMO_PROJECT_003',
    'Sobha Neopolis',
    'Sobha Limited',
    'Bengaluru',
    'Panathur',
    'East Bengaluru / ORR',
    'Apartment',
    '["1 BHK", "2 BHK", "3 BHK", "4 BHK"]'::jsonb,
    9500000.00,
    29000000.00,
    'Mid 2027',
    'Greek architecture-inspired luxury township near Outer Ring Road tech corridor.',
    '["Greek Themed", "Near Tech Parks", "Precast German Construction", "Multi-tier Security"]'::jsonb,
    '["Grand Amphitheatre", "4 Swimming Pools", "Co-working Lounge", "Indoor Sports Arena"]'::jsonb,
    'https://example.com/projects/sobha-neopolis',
    'ACTIVE'
),
(
    'DEMO_PROJECT_004',
    'Total Environment In That Quiet Earth',
    'Total Environment',
    'Bengaluru',
    'Hennur Main Road',
    'North-East Bengaluru',
    'Villa / Luxury Apartment',
    '["3 BHK", "4 BHK", "Duplex"]'::jsonb,
    24000000.00,
    55000000.00,
    'Ready to Move',
    'Artfully crafted homes with cantilevered terrace gardens and natural stone finishes.',
    '["Terrace Gardens", "Earthy Natural Materials", "Customized Interiors", "Green Roofing"]'::jsonb,
    '["Microbrewery Access", "Organic Farm", "Olympic Pool", "Library Cafe"]'::jsonb,
    'https://example.com/projects/total-environment-quiet-earth',
    'ACTIVE'
),
(
    'DEMO_PROJECT_005',
    'DLF The Arbour',
    'DLF Limited',
    'Gurgaon',
    'Sector 63',
    'Golf Course Extension',
    'Luxury High-Rise',
    '["4 BHK"]'::jsonb,
    75000000.00,
    110000000.00,
    'Mar 2028',
    'Ultra-luxury low-density residential towers on Golf Course Extension Road.',
    '["Golf Course Extension", "Double Height Lobbies", "Wrap-around Balconies", "Air Purification"]'::jsonb,
    '["Private Dining", "Temperature Controlled Pool", "Cigar Lounge", "Helipad Access"]'::jsonb,
    'https://example.com/projects/dlf-arbour',
    'ACTIVE'
),
(
    'DEMO_PROJECT_006',
    'M3M Golfestate Residenza',
    'M3M India',
    'Gurgaon',
    'Sector 65',
    'Golf Course Extension',
    'Apartment',
    '["3 BHK", "4 BHK", "Penthouse"]'::jsonb,
    32000000.00,
    65000000.00,
    'Ready to Move',
    '9-hole executive golf course facing luxury condominiums with 7-star resort ambiance.',
    '["Golf Course Facing", "Concierge Service", "Sky Lounges", "Rooftop Helipad"]'::jsonb,
    '["Golf Simulator", "Lawn Tennis", "Temperature Pool", "Kids Water Park"]'::jsonb,
    'https://example.com/projects/m3m-golfestate',
    'ACTIVE'
),
(
    'DEMO_PROJECT_007',
    'Lodha World One Reserve',
    'Lodha Group',
    'Mumbai',
    'Lower Parel',
    'South Central Mumbai',
    'Ultra Luxury High-Rise',
    '["3 BHK", "4 BHK", "5 BHK"]'::jsonb,
    95000000.00,
    220000000.00,
    'Ready to Move',
    'Iconic global architectural landmark with panoramic views of the Arabian Sea and city skyline.',
    '["Arabian Sea Views", "Armani/Casa Interiors", "Private Elevators", "Tri-level Sky Villas"]'::jsonb,
    '["Private Observatory", "World-class Spa", "Lap Pool", "Private Butler Service"]'::jsonb,
    'https://example.com/projects/lodha-world-one',
    'ACTIVE'
),
(
    'DEMO_PROJECT_008',
    'Piramal Mahalaxmi Central Tower',
    'Piramal Realty',
    'Mumbai',
    'Mahalaxmi',
    'South Mumbai',
    'Apartment',
    '["2 BHK", "3 BHK", "4 BHK"]'::jsonb,
    42000000.00,
    89000000.00,
    'Dec 2026',
    'Prestigious residential towers overlooking the Mahalaxmi Racecourse and the Arabian Sea.',
    '["Racecourse Views", "Sea Facing", "Smart Home Automation", "Acoustic Glazing"]'::jsonb,
    '["Observatory Deck", "Infinity Pool", "Yoga Pavilion", "Business Lounge"]'::jsonb,
    'https://example.com/projects/piramal-mahalaxmi',
    'ACTIVE'
),
(
    'DEMO_PROJECT_009',
    'Rustomjee Elements',
    'Rustomjee',
    'Mumbai',
    'Juhu Circle',
    'Western Suburbs',
    'Gated Community Luxury',
    '["3 BHK", "4 BHK", "5 BHK"]'::jsonb,
    65000000.00,
    140000000.00,
    'Ready to Move',
    'Celebrity-favored opulent gated enclave designed by James Law Cybertecture.',
    '["Celebrity Neighborhood", "Low Density 3 Acre Enclave", "Drop-off Porch", "High Security"]'::jsonb,
    '["40000 sqft Podiums", "Rooftop Lounge", "Private Screening Room", "Toddler Play Zone"]'::jsonb,
    'https://example.com/projects/rustomjee-elements',
    'ACTIVE'
),
(
    'DEMO_PROJECT_010',
    'My Home Bhooja',
    'My Home Group',
    'Hyderabad',
    'HITEC City',
    'Cyberabad Corridor',
    'Apartment',
    '["3 BHK", "4 BHK"]'::jsonb,
    28000000.00,
    58000000.00,
    'Ready to Move',
    'Iconic 36-floor luxury high-rise development next to Biodiversity Park and IT corridor.',
    '["HITEC City Core", "Biodiversity Park Facing", "Grand Entry Plaza", "IGBC Platinum Certified"]'::jsonb,
    '["78000 sqft Clubhouse", "Olympic Pool", "Billiards & Snooker", "Banquet Hall"]'::jsonb,
    'https://example.com/projects/my-home-bhooja',
    'ACTIVE'
),
(
    'DEMO_PROJECT_011',
    'Aparna Zenon',
    'Aparna Constructions',
    'Hyderabad',
    'Nanakramguda',
    'Financial District',
    'Apartment',
    '["2 BHK", "3 BHK"]'::jsonb,
    13500000.00,
    26000000.00,
    'Jun 2027',
    'Modern smart homes with EV charging infrastructure right in the heart of Financial District.',
    '["Financial District Walkable", "Future-ready Infrastructure", "High Rental Yield"]'::jsonb,
    '["Two Large Clubhouses", "Cricket Pitch", "Skating Rink", "Supermarket Arcade"]'::jsonb,
    'https://example.com/projects/aparna-zenon',
    'ACTIVE'
),
(
    'DEMO_PROJECT_012',
    'Panchshil Towers',
    'Panchshil Realty',
    'Pune',
    'Kharadi',
    'East Pune / IT Park',
    'Apartment / Penthouse',
    '["3 BHK", "4 BHK", "Podium Villa"]'::jsonb,
    29000000.00,
    62000000.00,
    'Ready to Move',
    'Contemporary high-rise towers near EON Free Zone designed by world-renowned architecture firms.',
    '["Near EON Free Zone", "VRV Air Conditioning", "Glass Facade", "Water Features"]'::jsonb,
    '["Pool Bar", "Gourmet Cafe", "Multi-sports Court", "Pet Park", "Yoga Terrace"]'::jsonb,
    'https://example.com/projects/panchshil-towers',
    'ACTIVE'
),
(
    'DEMO_PROJECT_013',
    'Kolte Patil Life Republic',
    'Kolte Patil',
    'Pune',
    'Hinjawadi',
    'West Pune IT Hub',
    'Integrated Township',
    '["2 BHK", "3 BHK", "Row House"]'::jsonb,
    6800000.00,
    16500000.00,
    'Dec 2026',
    '400-acre self-sustaining integrated township with international school and retail arcade.',
    '["400 Acre Township", "Walk to School", "Hinjawadi Phase 1 Close", "High ROI"]'::jsonb,
    '["Olympic Sports Complex", "Town Square", "Cycling Track", "Botanical Garden"]'::jsonb,
    'https://example.com/projects/kolte-patil-life-republic',
    'ACTIVE'
),
(
    'DEMO_PROJECT_014',
    'SmartWorld The Edition',
    'SmartWorld Developers',
    'Gurgaon',
    'Sector 66',
    'Golf Course Extension',
    'Apartment',
    '["3.5 BHK", "4.5 BHK"]'::jsonb,
    36000000.00,
    72000000.00,
    'Oct 2028',
    'Next-gen luxury residences with private elevator lobbies and luxury resort landscape.',
    '["Private Lift Lobbies", "270 Degree Views", "Centrally Located on GCER"]'::jsonb,
    '["Sky Deck", "Heated Swimming Pool", "Bowling Alley", "Alfresco Dining"]'::jsonb,
    'https://example.com/projects/smartworld-edition',
    'ACTIVE'
),
(
    'DEMO_PROJECT_015',
    'Brigade Calista',
    'Brigade Group',
    'Bengaluru',
    'Budigere Cross',
    'Old Madras Road Corridor',
    'Apartment',
    '["1.5 BHK", "2 BHK", "3 BHK"]'::jsonb,
    5800000.00,
    13500000.00,
    'Jun 2027',
    'Eco-friendly residential community featuring grand central courtyard with serene flora.',
    '["Eco-friendly Design", "Grand Central Courtyard", "Rapid Transit Connectivity", "High Value Growth"]'::jsonb,
    '["Grand Clubhouse", "Swimming Pool", "Reflexology Path", "Amphitheatre"]'::jsonb,
    'https://example.com/projects/brigade-calista',
    'ACTIVE'
)
ON CONFLICT (project_code) DO UPDATE SET
    project_name = EXCLUDED.project_name,
    developer_name = EXCLUDED.developer_name,
    city = EXCLUDED.city,
    locality = EXCLUDED.locality,
    micro_market = EXCLUDED.micro_market,
    property_type = EXCLUDED.property_type,
    configurations = EXCLUDED.configurations,
    price_min = EXCLUDED.price_min,
    price_max = EXCLUDED.price_max,
    possession = EXCLUDED.possession,
    project_description = EXCLUDED.project_description,
    features = EXCLUDED.features,
    amenities = EXCLUDED.amenities,
    project_url = EXCLUDED.project_url,
    status = EXCLUDED.status,
    updated_at = NOW();
